#!/usr/bin/env bash
# build_installer.sh — generates a self-extracting install/upgrade script for scrolldaddy-dns.
#
# Usage:
#   ./build_installer.sh [VERSION]
#
# If VERSION is omitted it is inferred from git tags (e.g. v1.2.3) or falls back to "dev".
#
# Output:
#   scrolldaddy-dns-installer.sh   — scp to the target server and run as root
#
# Typical workflow:
#   ./build_installer.sh 1.2.3
#   scp scrolldaddy-dns-installer.sh root@45.56.103.84:/tmp/
#   ssh root@45.56.103.84 bash /tmp/scrolldaddy-dns-installer.sh [--verbose]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="${SCRIPT_DIR}/dist"
OUTPUT="${SCRIPT_DIR}/scrolldaddy-dns-installer.sh"
STAGE_DIR="$(mktemp -d)"

cleanup() { rm -rf "$STAGE_DIR"; }
trap cleanup EXIT

# ── Version ───────────────────────────────────────────────────────────────────
VERSION="${1:-}"
if [ -z "$VERSION" ]; then
    VERSION="$(git -C "$SCRIPT_DIR" describe --tags --dirty 2>/dev/null || echo "dev")"
fi
VERSION="${VERSION#v}"   # strip leading 'v' if present
echo "Building installer for scrolldaddy-dns v${VERSION}..."

# ── Build binary (linux/amd64) ────────────────────────────────────────────────
echo "  Cross-compiling for linux/amd64..."
GOOS=linux GOARCH=amd64 go build \
    -ldflags "-X main.version=${VERSION}" \
    -o "${STAGE_DIR}/scrolldaddy-dns" \
    "${SCRIPT_DIR}/cmd/dns"
BINARY_SIZE="$(du -sh "${STAGE_DIR}/scrolldaddy-dns" | cut -f1)"
echo "  Build complete (${BINARY_SIZE})."

# ── Create payload tarball ────────────────────────────────────────────────────
echo "  Packaging payload..."
cp "${DIST_DIR}/scrolldaddy-dns.service"   "${STAGE_DIR}/"
cp "${DIST_DIR}/scrolldaddy.env.example"   "${STAGE_DIR}/"
cp "${DIST_DIR}/dns.json.example"          "${STAGE_DIR}/"

tar czf "${STAGE_DIR}/payload.tar.gz" \
    -C "${STAGE_DIR}" \
    scrolldaddy-dns \
    scrolldaddy-dns.service \
    scrolldaddy.env.example \
    dns.json.example

PAYLOAD_SIZE="$(du -sh "${STAGE_DIR}/payload.tar.gz" | cut -f1)"
PAYLOAD_B64="$(base64 < "${STAGE_DIR}/payload.tar.gz")"
echo "  Payload: ${PAYLOAD_SIZE} compressed, $(echo "$PAYLOAD_B64" | wc -c | tr -d ' ') bytes base64."

# ── Write installer script ────────────────────────────────────────────────────
echo "  Generating installer..."

# The installer is written in three parts:
#   1. A single-quoted heredoc for the fixed header (no variable expansion)
#   2. An echo that injects the build-time VERSION
#   3. A single-quoted heredoc for the fixed body (no variable expansion)
#   4. The base64 payload appended after __PAYLOAD__
# Single-quoting the heredoc delimiters ('EOF') prevents the build script from
# expanding variables inside those blocks — they will be literal $VARS in the output.

{
cat <<'INSTALLER_HEADER'
#!/usr/bin/env bash
# scrolldaddy-dns self-extracting installer
# Generated by build_installer.sh — do not edit manually.
#
# Usage: bash scrolldaddy-dns-installer.sh [--verbose]
#   Run as root. Installs or upgrades scrolldaddy-dns automatically.
#
# Fresh install:
#   Creates 'scrolldaddy' system user, /etc/scrolldaddy, /var/log/scrolldaddy.
#   Installs binary, systemd service, and example config files.
#   Creates /etc/scrolldaddy/scrolldaddy.env from example (if not present).
#   Does NOT start the service — edit the env file first, then:
#     systemctl enable --now scrolldaddy-dns
#
# Upgrade:
#   Stops the service, swaps the binary, restarts.
#   Updates service unit and example configs.
#   Never overwrites live configs (scrolldaddy.env, dns.json).
#   Rolls back automatically if the service fails to start.
set -euo pipefail

INSTALLER_HEADER

# Inject build-time version as a variable assignment
echo "INSTALLER_VERSION=\"${VERSION}\""

cat <<'INSTALLER_BODY'

SERVICE_NAME="scrolldaddy-dns"
BINARY_PATH="/usr/local/bin/scrolldaddy-dns"
SERVICE_FILE="/etc/systemd/system/scrolldaddy-dns.service"
ENV_DIR="/etc/scrolldaddy"
ENV_FILE="${ENV_DIR}/scrolldaddy.env"
ENV_EXAMPLE="${ENV_DIR}/scrolldaddy.env.example"
CONFIG_FILE="${ENV_DIR}/dns.json"
CONFIG_EXAMPLE="${ENV_DIR}/dns.json.example"
LOG_DIR="/var/log/scrolldaddy"
QUERY_LOG_DIR="${LOG_DIR}/queries"
SERVICE_USER="scrolldaddy"
STAGE_DIR="$(mktemp -d)"

cleanup() { rm -rf "$STAGE_DIR"; }
trap cleanup EXIT

# ── Helpers ───────────────────────────────────────────────────────────────────
VERBOSE=false
for arg in "$@"; do
    case "$arg" in --verbose|-v) VERBOSE=true ;; esac
done

log()         { echo "$@"; }
log_verbose() { [ "$VERBOSE" = true ] && echo "  $*" || true; }
die()         { echo "ERROR: $*" >&2; exit 1; }

# ── Preflight ─────────────────────────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || die "This installer must be run as root."
command -v systemctl >/dev/null 2>&1 || die "systemctl not found — is this a systemd system?"
command -v base64    >/dev/null 2>&1 || die "base64 not found."

# ── Detect mode ───────────────────────────────────────────────────────────────
detect_mode() {
    if [ -f "$BINARY_PATH" ]; then
        echo "upgrade"
    else
        echo "install"
    fi
}

# ── Extract payload ───────────────────────────────────────────────────────────
extract_payload() {
    log_verbose "Extracting payload..."
    local payload_line
    payload_line=$(awk '/^__PAYLOAD__$/{print NR+1; exit}' "$0")
    [ -n "$payload_line" ] || die "Payload marker not found — the installer file may be corrupt."
    tail -n +"$payload_line" "$0" | base64 -d | tar xzf - -C "$STAGE_DIR"
    log_verbose "Payload extracted to $STAGE_DIR."
}

# ── Install ───────────────────────────────────────────────────────────────────
do_install() {
    log ""
    log "Installing scrolldaddy-dns v${INSTALLER_VERSION} (fresh install)..."

    # Service user
    if ! id "$SERVICE_USER" >/dev/null 2>&1; then
        useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
        log_verbose "Created system user '$SERVICE_USER'."
    else
        log_verbose "User '$SERVICE_USER' already exists."
    fi

    # Directories
    mkdir -p "$ENV_DIR" "$LOG_DIR" "$QUERY_LOG_DIR"
    chown -R "${SERVICE_USER}:${SERVICE_USER}" "$LOG_DIR"
    log_verbose "Created: $ENV_DIR, $LOG_DIR, $QUERY_LOG_DIR"

    # Binary
    install -m 755 -o root -g root "${STAGE_DIR}/scrolldaddy-dns" "$BINARY_PATH"
    log_verbose "Installed binary: $BINARY_PATH"

    # Service unit
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy-dns.service" "$SERVICE_FILE"
    log_verbose "Installed service unit: $SERVICE_FILE"

    # Example configs (always written on install/upgrade)
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy.env.example" "$ENV_EXAMPLE"
    install -m 644 -o root -g root "${STAGE_DIR}/dns.json.example"        "$CONFIG_EXAMPLE"

    # Create live env file from example if not present
    if [ ! -f "$ENV_FILE" ]; then
        install -m 640 -o root -g "$SERVICE_USER" "${STAGE_DIR}/scrolldaddy.env.example" "$ENV_FILE"
        log "  Created $ENV_FILE from example."
    else
        log_verbose "  $ENV_FILE already exists — not overwritten."
    fi

    # Create live feature config from example if not present
    if [ ! -f "$CONFIG_FILE" ]; then
        install -m 644 -o root -g root "${STAGE_DIR}/dns.json.example" "$CONFIG_FILE"
        log_verbose "  Created $CONFIG_FILE from example."
    else
        log_verbose "  $CONFIG_FILE already exists — not overwritten."
    fi

    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"

    log ""
    log "============================================="
    log " Installation complete — action required     "
    log "============================================="
    log ""
    log " 1. Edit ${ENV_FILE}"
    log "    Set SCD_DB_NAME, SCD_DB_PASSWORD, SCD_API_KEY, etc."
    log ""
    log " 2. Start the service:"
    log "    systemctl start ${SERVICE_NAME}"
    log "    systemctl status ${SERVICE_NAME}"
    log ""
    log " 3. Verify:"
    log "    curl http://localhost:8053/health"
    log ""
}

# ── Upgrade ───────────────────────────────────────────────────────────────────
do_upgrade() {
    log ""
    log "Upgrading scrolldaddy-dns to v${INSTALLER_VERSION}..."

    # Back up current binary for rollback
    cp "$BINARY_PATH" "${BINARY_PATH}.bak"
    log_verbose "Backed up existing binary to ${BINARY_PATH}.bak"

    # Update example configs (never touch live configs)
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy.env.example" "$ENV_EXAMPLE"
    install -m 644 -o root -g root "${STAGE_DIR}/dns.json.example"        "$CONFIG_EXAMPLE"
    log_verbose "Updated example configs."

    # Update service unit
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy-dns.service" "$SERVICE_FILE"
    systemctl daemon-reload
    log_verbose "Updated service unit."

    # Stop → swap → start
    local was_running=false
    if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
        was_running=true
        log_verbose "Stopping ${SERVICE_NAME}..."
        systemctl stop "$SERVICE_NAME"
    fi

    install -m 755 -o root -g root "${STAGE_DIR}/scrolldaddy-dns" "$BINARY_PATH"
    log_verbose "Installed new binary: $BINARY_PATH"

    if [ "$was_running" = true ]; then
        systemctl start "$SERVICE_NAME"

        # Wait up to 10 seconds for the service to become active
        local ok=false
        for _ in 1 2 3 4 5 6 7 8 9 10; do
            sleep 1
            if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
                ok=true
                break
            fi
        done

        if [ "$ok" = true ]; then
            rm -f "${BINARY_PATH}.bak"
            log_verbose "Service started successfully."
        else
            log "Service failed to start — rolling back..."
            install -m 755 -o root -g root "${BINARY_PATH}.bak" "$BINARY_PATH"
            rm -f "${BINARY_PATH}.bak"
            systemctl start "$SERVICE_NAME" || true
            die "Upgrade failed. Check logs: journalctl -u ${SERVICE_NAME}"
        fi
    else
        rm -f "${BINARY_PATH}.bak"
        log "  Service was not running — binary replaced but not started."
        log "  Start when ready: systemctl start ${SERVICE_NAME}"
    fi

    log ""
    log "============================================="
    log " Upgrade complete: v${INSTALLER_VERSION}      "
    log "============================================="
    log ""
    log " Status: systemctl status ${SERVICE_NAME}"
    log " Health: curl http://localhost:8053/health"
    log " Stats:  curl http://localhost:8053/stats"
    log ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
log "============================================="
log " ScrollDaddy DNS Installer v${INSTALLER_VERSION}"
log "============================================="

extract_payload

MODE="$(detect_mode)"
log_verbose "Mode: $MODE"

case "$MODE" in
    install) do_install ;;
    upgrade) do_upgrade ;;
    *) die "Unknown mode: $MODE" ;;
esac

exit 0
__PAYLOAD__
INSTALLER_BODY

# Append the base64-encoded payload (no trailing newline issues — base64 output ends with newline)
printf '%s\n' "$PAYLOAD_B64"

} > "$OUTPUT"

chmod +x "$OUTPUT"

INSTALLER_SIZE="$(du -sh "$OUTPUT" | cut -f1)"
echo "  Installer: $OUTPUT (${INSTALLER_SIZE})"
echo ""
echo "Deploy:"
echo "  scp scrolldaddy-dns/scrolldaddy-dns-installer.sh root@45.56.103.84:/tmp/"
echo "  ssh root@45.56.103.84 bash /tmp/scrolldaddy-dns-installer.sh [--verbose]"
