#!/usr/bin/env bash
# build_installer.sh — generates a self-extracting install/upgrade script for scrolldaddy-dns.
#
# Usage:
#   ./build_installer.sh [VERSION]
#
# If VERSION is omitted it is inferred from git tags (e.g. v1.2.3) or falls back to "dev".
#
# Output:
#   scrolldaddy-dns-installer.sh   — scp to the target server and run as root
#
# Typical workflow:
#   ./build_installer.sh 1.2.3
#   scp scrolldaddy-dns-installer.sh root@<SERVER_IP>:/tmp/
#   ssh root@<SERVER_IP> bash /tmp/scrolldaddy-dns-installer.sh [--verbose]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="${SCRIPT_DIR}/dist"
OUTPUT="${SCRIPT_DIR}/scrolldaddy-dns-installer.sh"
STAGE_DIR="$(mktemp -d)"

cleanup() { rm -rf "$STAGE_DIR"; }
trap cleanup EXIT

# ── Version ───────────────────────────────────────────────────────────────────
VERSION="${1:-}"
if [ -z "$VERSION" ]; then
    VERSION="$(git -C "$SCRIPT_DIR" describe --tags --dirty 2>/dev/null || echo "dev")"
fi
VERSION="${VERSION#v}"   # strip leading 'v' if present
echo "Building installer for scrolldaddy-dns v${VERSION}..."

# ── Build binary (linux/amd64) ────────────────────────────────────────────────
echo "  Cross-compiling for linux/amd64..."
GOOS=linux GOARCH=amd64 go build \
    -ldflags "-X main.version=${VERSION}" \
    -o "${STAGE_DIR}/scrolldaddy-dns" \
    "${SCRIPT_DIR}/cmd/dns"
BINARY_SIZE="$(du -sh "${STAGE_DIR}/scrolldaddy-dns" | cut -f1)"
echo "  Build complete (${BINARY_SIZE})."

# ── Create payload tarball ────────────────────────────────────────────────────
echo "  Packaging payload..."
cp "${DIST_DIR}/scrolldaddy-dns.service"   "${STAGE_DIR}/"
cp "${DIST_DIR}/scrolldaddy.env.example"   "${STAGE_DIR}/"
cp "${DIST_DIR}/dns.json.example"          "${STAGE_DIR}/"

tar czf "${STAGE_DIR}/payload.tar.gz" \
    -C "${STAGE_DIR}" \
    scrolldaddy-dns \
    scrolldaddy-dns.service \
    scrolldaddy.env.example \
    dns.json.example

PAYLOAD_SIZE="$(du -sh "${STAGE_DIR}/payload.tar.gz" | cut -f1)"
PAYLOAD_B64="$(base64 < "${STAGE_DIR}/payload.tar.gz")"
echo "  Payload: ${PAYLOAD_SIZE} compressed, $(echo "$PAYLOAD_B64" | wc -c | tr -d ' ') bytes base64."

# ── Write installer script ────────────────────────────────────────────────────
echo "  Generating installer..."

# The installer is written in three parts:
#   1. A single-quoted heredoc for the fixed header (no variable expansion)
#   2. An echo that injects the build-time VERSION
#   3. A single-quoted heredoc for the fixed body (no variable expansion)
#   4. The base64 payload appended after __PAYLOAD__
# Single-quoting the heredoc delimiters ('EOF') prevents the build script from
# expanding variables inside those blocks — they will be literal $VARS in the output.

{
cat <<'INSTALLER_HEADER'
#!/usr/bin/env bash
# scrolldaddy-dns self-extracting installer
# Generated by build_installer.sh — do not edit manually.
#
# Usage: bash scrolldaddy-dns-installer.sh [--verbose] [--non-interactive]
#   Run as root. Installs or upgrades scrolldaddy-dns automatically.
#
# Fresh install (interactive):
#   Walks through database credentials, DoH domain, API key setup.
#   Installs Caddy (HTTPS reverse proxy) and configures ufw firewall.
#   Starts the service when setup is complete.
#
# Fresh install (non-interactive):
#   Creates files and directories, writes example configs, enables service.
#   Does NOT start the service — edit /etc/scrolldaddy/scrolldaddy.env first.
#   Use: bash scrolldaddy-dns-installer.sh --non-interactive
#
# Upgrade:
#   Stops the service, swaps the binary, restarts.
#   Updates service unit and example configs.
#   Never overwrites live configs (scrolldaddy.env, dns.json).
#   Rolls back automatically if the service fails to start.
set -euo pipefail

INSTALLER_HEADER

# Inject build-time version as a variable assignment
echo "INSTALLER_VERSION=\"${VERSION}\""

cat <<'INSTALLER_BODY'

SERVICE_NAME="scrolldaddy-dns"
BINARY_PATH="/usr/local/bin/scrolldaddy-dns"
SERVICE_FILE="/etc/systemd/system/scrolldaddy-dns.service"
ENV_DIR="/etc/scrolldaddy"
ENV_FILE="${ENV_DIR}/scrolldaddy.env"
ENV_EXAMPLE="${ENV_DIR}/scrolldaddy.env.example"
CONFIG_FILE="${ENV_DIR}/dns.json"
CONFIG_EXAMPLE="${ENV_DIR}/dns.json.example"
LOG_DIR="/var/log/scrolldaddy"
QUERY_LOG_DIR="${LOG_DIR}/queries"
SERVICE_USER="scrolldaddy"
STAGE_DIR="$(mktemp -d)"

# ── Gathered setup values (populated by interactive_setup) ────────────────────
DB_HOST="" DB_PORT="" DB_NAME="" DB_USER="" DB_PASSWORD=""
DOH_DOMAIN="" API_KEY=""
DOT_CERT_FILE="" DOT_KEY_FILE="" DOT_BASE_DOMAIN=""
LOG_LEVEL="info"

cleanup() { rm -rf "$STAGE_DIR"; }
trap cleanup EXIT

# ── Flag parsing ──────────────────────────────────────────────────────────────
VERBOSE=false
NONINTERACTIVE=false
for arg in "$@"; do
    case "$arg" in
        --verbose|-v)         VERBOSE=true ;;
        --non-interactive|-n) NONINTERACTIVE=true ;;
    esac
done

# ── Basic helpers ─────────────────────────────────────────────────────────────
log()         { echo "$@"; }
log_verbose() { [ "$VERBOSE" = true ] && echo "  $*" || true; }
die()         { echo ""; echo "ERROR: $*" >&2; exit 1; }
print_section() { echo ""; echo "── $* ─────────────────────────────────"; }

# ── Interactive prompt helpers ─────────────────────────────────────────────────

# prompt "Label" "default" VARNAME
prompt() {
    local label="$1" default="$2" varname="$3"
    local value
    if [ -n "$default" ]; then
        read -r -p "  ${label} [${default}]: " value || true
        value="${value:-$default}"
    else
        read -r -p "  ${label}: " value || true
    fi
    printf -v "$varname" '%s' "$value"
}

# prompt_required "Label" VARNAME  — loops until non-empty
prompt_required() {
    local label="$1" varname="$2"
    local value=""
    while [ -z "$value" ]; do
        read -r -p "  ${label}: " value || true
        [ -z "$value" ] && echo "  (required)"
    done
    printf -v "$varname" '%s' "$value"
}

# prompt_secret "Label" VARNAME  — no echo, loops until non-empty
prompt_secret() {
    local label="$1" varname="$2"
    local value=""
    while [ -z "$value" ]; do
        read -r -s -p "  ${label}: " value || true
        echo ""
        [ -z "$value" ] && echo "  (required)"
    done
    printf -v "$varname" '%s' "$value"
}

# prompt_yn "Label" "y|n" VARNAME  — sets VARNAME to "true" or "false"
prompt_yn() {
    local label="$1" default="$2" varname="$3"
    local prompt_str value
    if [ "$default" = "y" ]; then
        prompt_str="  ${label} [Y/n]: "
    else
        prompt_str="  ${label} [y/N]: "
    fi
    read -r -p "$prompt_str" value || true
    value="${value:-$default}"
    case "$(echo "$value" | tr '[:upper:]' '[:lower:]')" in
        y|yes) printf -v "$varname" 'true' ;;
        *)     printf -v "$varname" 'false' ;;
    esac
}

generate_api_key() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        tr -dc 'a-f0-9' < /dev/urandom | head -c 64
    fi
}

# ── Preflight ─────────────────────────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || die "This installer must be run as root."
command -v systemctl >/dev/null 2>&1 || die "systemctl not found — is this a systemd system?"
command -v base64    >/dev/null 2>&1 || die "base64 not found."

# ── Detect mode ───────────────────────────────────────────────────────────────
detect_mode() {
    if [ -f "$BINARY_PATH" ]; then
        echo "upgrade"
    else
        echo "install"
    fi
}

# ── Extract payload ───────────────────────────────────────────────────────────
extract_payload() {
    log_verbose "Extracting payload..."
    local payload_line
    payload_line=$(awk '/^__PAYLOAD__$/{print NR+1; exit}' "$0")
    [ -n "$payload_line" ] || die "Payload marker not found — the installer file may be corrupt."
    tail -n +"$payload_line" "$0" | base64 -d | tar xzf - -C "$STAGE_DIR"
    log_verbose "Payload extracted to $STAGE_DIR."
}

# ── Env file writer ───────────────────────────────────────────────────────────
write_env_file() {
    cat > "$ENV_FILE" <<ENV_EOF
# ScrollDaddy DNS Server — Environment Configuration
# Written by installer v${INSTALLER_VERSION} on $(date -u '+%Y-%m-%d %H:%M UTC')

# ── Database ──────────────────────────────────────────────────────────────────
SCD_DB_HOST=${DB_HOST}
SCD_DB_PORT=${DB_PORT}
SCD_DB_NAME=${DB_NAME}
SCD_DB_USER=${DB_USER}
SCD_DB_PASSWORD=${DB_PASSWORD}

# ── Server Ports ──────────────────────────────────────────────────────────────
# DoH: Caddy proxies HTTPS 443 → this port
SCD_DOH_PORT=8053
SCD_DOT_PORT=853

# ── DNS-over-TLS (leave blank to disable) ─────────────────────────────────────
SCD_DOT_CERT_FILE=${DOT_CERT_FILE}
SCD_DOT_KEY_FILE=${DOT_KEY_FILE}
SCD_DOT_BASE_DOMAIN=${DOT_BASE_DOMAIN}

# ── Upstream DNS ──────────────────────────────────────────────────────────────
SCD_UPSTREAM_PRIMARY=1.1.1.1:53
SCD_UPSTREAM_SECONDARY=8.8.8.8:53

# ── Reload Intervals ──────────────────────────────────────────────────────────
SCD_RELOAD_INTERVAL=60
SCD_BLOCKLIST_RELOAD_INTERVAL=3600

# ── API Key ───────────────────────────────────────────────────────────────────
# Protects /reload, /cache/flush, /device/{uid}/log endpoints
SCD_API_KEY=${API_KEY}

# ── Logging ───────────────────────────────────────────────────────────────────
SCD_LOG_LEVEL=${LOG_LEVEL}
SCD_LOG_FILE=/var/log/scrolldaddy/dns.log
ENV_EOF
    chown root:"$SERVICE_USER" "$ENV_FILE"
    chmod 640 "$ENV_FILE"
}

# ── Caddy ─────────────────────────────────────────────────────────────────────
install_caddy() {
    if command -v caddy >/dev/null 2>&1; then
        log_verbose "Caddy is already installed ($(caddy version 2>/dev/null | head -1))."
        return 0
    fi

    log "Installing Caddy..."
    if ! command -v apt-get >/dev/null 2>&1; then
        log "  WARN: apt-get not found — install Caddy manually: https://caddyserver.com/docs/install"
        log "  Then add a reverse proxy for ${DOH_DOMAIN} → localhost:8053 (paths /resolve/*, /health)."
        return 0
    fi

    apt-get install -y -q debian-keyring debian-archive-keyring apt-transport-https curl 2>/dev/null || true
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        | tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null
    apt-get update -q
    apt-get install -y -q caddy
    systemctl enable caddy >/dev/null
    log "  Caddy installed."
}

configure_caddy() {
    local domain="$1"
    local caddyfile="/etc/caddy/Caddyfile"
    local marker="# scrolldaddy-dns — managed by installer"

    # Idempotent: already configured
    if grep -q "$marker" "$caddyfile" 2>/dev/null; then
        log_verbose "Caddy already configured for scrolldaddy-dns."
        return 0
    fi

    # Back up existing Caddyfile
    [ -f "$caddyfile" ] && cp "$caddyfile" "${caddyfile}.bak"

    local our_block
    our_block="${marker}
${domain} {
    handle /resolve/* {
        reverse_proxy localhost:8053
    }
    handle /health {
        reverse_proxy localhost:8053
    }
    respond 404
}"

    # Replace the default placeholder Caddyfile (contains ':80'); otherwise append
    if grep -q '^:80' "$caddyfile" 2>/dev/null; then
        echo "$our_block" > "$caddyfile"
        log_verbose "Replaced default Caddyfile."
    else
        { echo ""; echo "$our_block"; } >> "$caddyfile"
        log_verbose "Appended to existing Caddyfile."
    fi

    systemctl reload caddy 2>/dev/null || systemctl restart caddy
    log "  Caddy configured for ${domain} (automatic HTTPS via Let's Encrypt)."
    log "  Ensure ${domain} has an A record pointing to this server's IP."
}

# ── Firewall ──────────────────────────────────────────────────────────────────
configure_firewall() {
    if ! command -v ufw >/dev/null 2>&1; then
        log_verbose "ufw not found — skipping firewall setup."
        return 0
    fi

    local ufw_status
    ufw_status="$(ufw status 2>/dev/null | head -1 || echo "")"

    if echo "$ufw_status" | grep -q "inactive"; then
        log "Enabling ufw firewall..."
        # Ensure SSH stays open before enabling
        ufw allow ssh >/dev/null
        ufw allow 443/tcp comment 'scrolldaddy-dns DoH (via Caddy)' >/dev/null
        ufw allow 853/tcp comment 'scrolldaddy-dns DoT' >/dev/null
        ufw --force enable >/dev/null
        log "  Firewall enabled: SSH, 443/tcp, 853/tcp allowed. 8053 blocked externally."
    else
        ufw allow 443/tcp comment 'scrolldaddy-dns DoH (via Caddy)' >/dev/null
        ufw allow 853/tcp comment 'scrolldaddy-dns DoT' >/dev/null
        log "  Firewall rules added: 443/tcp, 853/tcp. 8053 remains blocked externally."
    fi
}

# ── Interactive setup ─────────────────────────────────────────────────────────
interactive_setup() {
    if [ ! -t 0 ]; then
        die "Interactive setup requires a TTY. Use --non-interactive for scripted installs."
    fi

    echo ""
    echo "╔═══════════════════════════════════════════╗"
    echo "║  ScrollDaddy DNS Setup                    ║"
    echo "╚═══════════════════════════════════════════╝"

    # ── Database
    print_section "Database"
    prompt          "Host"     "localhost"        DB_HOST
    prompt          "Port"     "5432"             DB_PORT
    prompt_required "Name"                        DB_NAME
    prompt          "User"     "scrolldaddy_dns"  DB_USER
    prompt_secret   "Password"                    DB_PASSWORD

    # ── DoH domain
    print_section "DNS-over-HTTPS"
    log "  Caddy will obtain a TLS certificate automatically (Let's Encrypt)."
    log "  Make sure an A record for this domain points to this server."
    prompt_required "Public domain (e.g. dns.example.com)" DOH_DOMAIN

    # ── API key
    print_section "API Key"
    log "  Protects /reload, /cache/flush, and device log endpoints."
    local generated_key
    generated_key="$(generate_api_key)"
    local api_key_input=""
    read -r -p "  API key [Enter to auto-generate]: " api_key_input || true
    if [ -z "$api_key_input" ]; then
        API_KEY="$generated_key"
        log "  Generated API key: ${API_KEY}"
        log "  Save this — you will need it to call protected API endpoints."
    else
        API_KEY="$api_key_input"
    fi

    # ── DoT (optional)
    print_section "DNS-over-TLS (optional)"
    log "  Requires a wildcard TLS certificate (e.g. *.dns.example.com)."
    local setup_dot="false"
    prompt_yn "Configure DoT?" "n" setup_dot
    if [ "$setup_dot" = "true" ]; then
        prompt_required "Certificate file path" DOT_CERT_FILE
        prompt_required "Key file path"         DOT_KEY_FILE
        prompt_required "Base domain"           DOT_BASE_DOMAIN
    fi

    # ── Log level
    print_section "Logging"
    prompt "Level (debug/info/warn/error)" "info" LOG_LEVEL

    # ── Connectivity test
    echo ""
    if command -v nc >/dev/null 2>&1; then
        if nc -z -w5 "$DB_HOST" "$DB_PORT" 2>/dev/null; then
            log "Database TCP connectivity to ${DB_HOST}:${DB_PORT}: OK"
        else
            log "WARN: Cannot reach ${DB_HOST}:${DB_PORT} — check host/port and firewall."
            log "      The service will retry the connection automatically after start."
        fi
    fi

    # ── Write env file
    echo ""
    write_env_file
    log "Wrote ${ENV_FILE}"
}

# ── Install ───────────────────────────────────────────────────────────────────
do_install() {
    log ""
    log "Installing scrolldaddy-dns v${INSTALLER_VERSION}..."

    # Service user
    if ! id "$SERVICE_USER" >/dev/null 2>&1; then
        useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
        log_verbose "Created system user '${SERVICE_USER}'."
    else
        log_verbose "User '${SERVICE_USER}' already exists."
    fi

    # Directories
    mkdir -p "$ENV_DIR" "$LOG_DIR" "$QUERY_LOG_DIR"
    chown -R "${SERVICE_USER}:${SERVICE_USER}" "$LOG_DIR"
    log_verbose "Created: ${ENV_DIR}, ${LOG_DIR}, ${QUERY_LOG_DIR}"

    # Binary
    install -m 755 -o root -g root "${STAGE_DIR}/scrolldaddy-dns" "$BINARY_PATH"
    log_verbose "Installed binary: ${BINARY_PATH}"

    # Service unit
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy-dns.service" "$SERVICE_FILE"
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME" >/dev/null
    log_verbose "Installed and enabled systemd service."

    # Example configs (always written)
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy.env.example" "$ENV_EXAMPLE"
    install -m 644 -o root -g root "${STAGE_DIR}/dns.json.example"        "$CONFIG_EXAMPLE"

    # Feature config from example if not present
    if [ ! -f "$CONFIG_FILE" ]; then
        install -m 644 -o root -g root "${STAGE_DIR}/dns.json.example" "$CONFIG_FILE"
        log_verbose "Created ${CONFIG_FILE} from example."
    fi

    if [ "$NONINTERACTIVE" = true ]; then
        # Non-interactive: write env from example, leave service stopped
        if [ ! -f "$ENV_FILE" ]; then
            install -m 640 -o root -g "$SERVICE_USER" "${STAGE_DIR}/scrolldaddy.env.example" "$ENV_FILE"
        fi
        echo ""
        echo "╔═══════════════════════════════════════════╗"
        echo "║  Installation complete (non-interactive)  ║"
        echo "╚═══════════════════════════════════════════╝"
        echo ""
        echo " Next steps:"
        echo "   1. Edit ${ENV_FILE}"
        echo "      Set SCD_DB_NAME, SCD_DB_PASSWORD, SCD_API_KEY, etc."
        echo ""
        echo "   2. Start the service:"
        echo "      systemctl start ${SERVICE_NAME}"
        echo "      systemctl status ${SERVICE_NAME}"
        echo ""
        echo "   3. Verify:"
        echo "      curl http://localhost:8053/health"
        echo ""
        return 0
    fi

    # Interactive: setup wizard → Caddy → firewall → start
    interactive_setup
    install_caddy
    configure_caddy "$DOH_DOMAIN"
    configure_firewall

    # Start the service
    echo ""
    log "Starting scrolldaddy-dns..."
    systemctl start "$SERVICE_NAME"

    # Wait for startup (blocklist load takes ~10s on first run)
    local started=false
    for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        sleep 1
        if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
            started=true
            break
        fi
    done

    echo ""
    if [ "$started" = true ]; then
        local health
        health="$(curl -sf http://localhost:8053/health 2>/dev/null || echo '(pending)')"
        echo "╔═══════════════════════════════════════════╗"
        echo "║  Installation complete!                   ║"
        echo "╚═══════════════════════════════════════════╝"
        echo ""
        echo " Health:  ${health}"
        echo " (db_connected may be false for ~30s while the blocklist loads)"
        echo ""
        echo " Useful commands:"
        echo "   tail -f ${LOG_DIR}/dns.log"
        echo "   curl http://localhost:8053/stats"
        echo "   curl http://localhost:8053/health"
        echo "   systemctl status ${SERVICE_NAME}"
        echo ""
        if [ -n "$API_KEY" ]; then
            echo " API key: ${API_KEY}"
            echo " (also saved in ${ENV_FILE})"
            echo ""
        fi
    else
        echo "WARN: Service did not start within 15 seconds."
        echo "Check logs: journalctl -u ${SERVICE_NAME} --no-pager -n 30"
        echo ""
        echo "Common causes:"
        echo "  - Database unreachable (check SCD_DB_HOST/PORT/NAME/PASSWORD in ${ENV_FILE})"
        echo "  - fail_mode=closed in ${CONFIG_FILE} and DB not yet available"
        echo ""
    fi
}

# ── Upgrade ───────────────────────────────────────────────────────────────────
do_upgrade() {
    log ""
    log "Upgrading scrolldaddy-dns to v${INSTALLER_VERSION}..."

    # Back up current binary for rollback
    cp "$BINARY_PATH" "${BINARY_PATH}.bak"
    log_verbose "Backed up existing binary to ${BINARY_PATH}.bak"

    # Update example configs (never touch live configs)
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy.env.example" "$ENV_EXAMPLE"
    install -m 644 -o root -g root "${STAGE_DIR}/dns.json.example"        "$CONFIG_EXAMPLE"
    log_verbose "Updated example configs."

    # Update service unit
    install -m 644 -o root -g root "${STAGE_DIR}/scrolldaddy-dns.service" "$SERVICE_FILE"
    systemctl daemon-reload
    log_verbose "Updated service unit."

    # Stop the service unconditionally — handles running, crash-looping, and
    # already-stopped states. 'reset-failed' clears any failed state so
    # is-enabled check works correctly and NRestarts resets to 0.
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    systemctl reset-failed "$SERVICE_NAME" 2>/dev/null || true
    log_verbose "Stopped ${SERVICE_NAME}."

    install -m 755 -o root -g root "${STAGE_DIR}/scrolldaddy-dns" "$BINARY_PATH"
    log_verbose "Installed new binary: $BINARY_PATH"

    # Only restart if the service is enabled (i.e. it was set up to run).
    # This preserves a deliberate "installed but stopped for maintenance" state.
    if systemctl is-enabled --quiet "$SERVICE_NAME" 2>/dev/null; then
        systemctl start "$SERVICE_NAME"

        # Wait for the service to stabilise. We check both that it is active
        # AND that NRestarts is 0 — a service can briefly appear "active"
        # between crash-loop restarts, giving a false positive if we only
        # checked is-active. reset-failed above ensures NRestarts starts at 0.
        local ok=false
        for _ in 1 2 3 4 5 6 7 8 9 10 11 12; do
            sleep 1
            if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
                restarts="$(systemctl show "$SERVICE_NAME" --property=NRestarts --value 2>/dev/null || echo 1)"
                if [ "${restarts}" = "0" ]; then
                    ok=true
                    break
                fi
            fi
        done

        if [ "$ok" = true ]; then
            rm -f "${BINARY_PATH}.bak"
            log_verbose "Service started successfully."
        else
            log "Service failed to start — rolling back..."
            install -m 755 -o root -g root "${BINARY_PATH}.bak" "$BINARY_PATH"
            rm -f "${BINARY_PATH}.bak"
            systemctl start "$SERVICE_NAME" || true
            die "Upgrade failed. Check logs: journalctl -u ${SERVICE_NAME}"
        fi
    else
        rm -f "${BINARY_PATH}.bak"
        log "  Service is not enabled — binary replaced but not started."
        log "  Start when ready: systemctl enable --now ${SERVICE_NAME}"
    fi

    log ""
    echo "╔═══════════════════════════════════════════╗"
    printf "║  Upgrade complete: v%-22s║\n" "${INSTALLER_VERSION}  "
    echo "╚═══════════════════════════════════════════╝"
    log ""
    log " Status: systemctl status ${SERVICE_NAME}"
    log " Health: curl http://localhost:8053/health"
    log " Stats:  curl http://localhost:8053/stats"
    log ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
echo ""
echo "╔═══════════════════════════════════════════╗"
printf "║  ScrollDaddy DNS Installer v%-14s║\n" "${INSTALLER_VERSION}  "
echo "╚═══════════════════════════════════════════╝"

extract_payload

MODE="$(detect_mode)"
log_verbose "Mode: $MODE"

case "$MODE" in
    install) do_install ;;
    upgrade) do_upgrade ;;
    *) die "Unknown mode: $MODE" ;;
esac

exit 0
__PAYLOAD__
INSTALLER_BODY

# Append the base64-encoded payload (no trailing newline issues — base64 output ends with newline)
printf '%s\n' "$PAYLOAD_B64"

} > "$OUTPUT"

chmod +x "$OUTPUT"

INSTALLER_SIZE="$(du -sh "$OUTPUT" | cut -f1)"
echo "  Installer: $OUTPUT (${INSTALLER_SIZE})"
echo ""
echo "Deploy:"
echo "  scp scrolldaddy-dns/scrolldaddy-dns-installer.sh root@<SERVER_IP>:/tmp/"
echo "  ssh root@<SERVER_IP> bash /tmp/scrolldaddy-dns-installer.sh [--verbose]"
